### ISSUE TITLE
Reverse string

### ISSUE THREAD

**Issue by ryankeener** [bean710/holbertonschool-low_level_programming#10]
https://github.com/bean710/holbertonschool-low_level_programming/blob/8b85ae5620db569c413dced584feee99b0798191/0x05-pointers_arrays_strings/5-rev_string.c#L13

Instead of manipulating `s` I'd recommend initializing a new variable (`s1`?) and using that to traverse the characters in the string. That way `s` will always be a pointer to the beginning of your memory space for the string. I think that could clean up a bit of what you're doing.

It can be helpful to break down the problem into its component parts of functionality (which you've effectively done):

1. Determine length of `s`
2. Allocate new memory space for a copy `s'` of `s`
3. Copy the contents of `s` into `s'`
4. Walk through `s'` and overwrite `s`

Then you can review those components to see if any can be eliminated or consolidated.

Ultimately you're going to have to have 'creative' solutions like this due to the restrictions being placed on you for these assignments.

**Comment by ryankeener** [comment]
One other thing:
I'm not sure this line is necessary since this last bit of memory should already contain `\0`
https://github.com/bean710/holbertonschool-low_level_programming/blob/8b85ae5620db569c413dced584feee99b0798191/0x05-pointers_arrays_strings/5-rev_string.c#L28

**Comment by bean710** [comment]
I think adding another pointer would make it less intuitive and messier. It seems like I have the correct steps and consolidating them would just lead to confusion.

**Comment by bean710** [comment]
Nevermind, I can consolidate. Reopening.

**Comment by ryankeener** [comment]
All good. My thinking was that `s` always points to the beginning of the memory holding the original string but it's not necessary as long as you can find your way back (via `len` etc)
