### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by ryankeener** [bean710/holbertonschool-low_level_programming#4]
https://github.com/bean710/holbertonschool-low_level_programming/blob/870a626cef02a876bc281dfd9bebc21272aa3401/0x02-functions_nested_loops/9-times_table.c#L8

This is _much_ easier if you can use the `math` lib and `printf` (but I'm guessing you already know that)
```c
void times_table(void) {
  int i, j;
  int upto = 9;
  
  for (i = 0; i <= upto; i++) {
    for (j = 0; j <= upto; j++) {
      int num = i * j;
      int colWidth = (int)log10(j * upto) + 2;
      char terminator = j < upto ? ',' : '\n';
      printf("%*d%c", colWidth, num, terminator);
    }
  }
}
```

This one doesn't use any other libraries but loses the variable width columns.

```c
void times_table(void) {
  int i, j;
  int upto = 9;
  int colWidth = 3;
  
  for (i = 0; i <= upto; i++) {
  	for (j = 0; j <= upto; j++) {
  		int num = i * j;

	  	putInt(num, colWidth);
  		
  		j < upto ? putchar(',') : putchar('\n');
  	}
  }
}
```

**Comment by ryankeener** [comment]
How much would you give me for the `putInt` code? 😛

**Comment by ryankeener** [comment]
```c
void putInt(int x, int maxWidth) {
	int y = x/10;
	if (y > 0) {
		putInt(y, maxWidth - 1);
	} else {
		for (int s = 0; s < maxWidth; s++) {
			putchar(' ');
		}	
	}
	
	putchar('0' + x%10);
}
```

**Comment by bean710** [comment]
This was just a temporary fix while I worked on a totally over-engineered, but super flexible and readable version. Will replace.

**Comment by bean710** [comment]
Actually this is fine, I'm leaving it.
