### ISSUE TITLE
Power function

### ISSUE THREAD

**Issue by ryankeener** [bean710/holbertonschool-low_level_programming#5]
https://github.com/bean710/holbertonschool-low_level_programming/blob/e9389a0d0cab75e5bf7757711ed41ee0431af45c/0x02-functions_nested_loops/100-times_table.c#L53-L64

I guess you're accuracy with this function is limited by the fact that you can only return an `int` so negative exponents won't really work. However, you can save some cycles by returning early if `b <=0`

```c
 int _pow(int a, int b) 
 { 
 	int i, ans; 

 	if (b <= 0)
 	 	return 1;
  
 	ans = a; 
 	for (i = 0; i < b - 1; i++) 
 	{ 
 		ans *= ans; 
 	} 
  
 	return ans; 
 } 
```

**Comment by bean710** [comment]
This power function was totally wrong, too! Ended up fixing it, will add this, too.
