### ISSUE TITLE
Alternative implementation of getlen

### ISSUE THREAD

**Issue by ryankeener** [bean710/holbertonschool-low_level_programming#6]
https://github.com/bean710/holbertonschool-low_level_programming/blob/e9389a0d0cab75e5bf7757711ed41ee0431af45c/0x02-functions_nested_loops/100-times_table.c#L88-L99

This is absolutely fine but you could also use a `for` loop

```c
int getlen(int num)
{
	int i;
	for (i = 1; num > 9; i++) {
		num /= 10;
	}
	return i;
}
```

Another thing to mention is that both of our implementations will always return `1` if `num` is negative.  It'd be better to either use the absolute value of `num` (if you want to support negative numbers) or return `-1` to signify an error condition (since `-1` doesn't make sense as a length value.)

**Comment by bean710** [comment]
Fixed negative number handling in [this](https://github.com/bean710/holbertonschool-low_level_programming/commit/f882ced93daa971b725fde27527223bcf0d3bf0e#diff-a16b9ba583417355632800fd04617b99) commit.
