### ISSUE TITLE
variable initialization

### ISSUE THREAD

**Issue by ryankeener** [bean710/holbertonschool-low_level_programming#7]
https://github.com/bean710/holbertonschool-low_level_programming/blob/e9389a0d0cab75e5bf7757711ed41ee0431af45c/0x02-functions_nested_loops/100-times_table.c#L73-L80

I'm not too familiar with `c` best practices but is there a reason you don't initialize the variable in the declaration? E.g.
```c
  int l = getlen(num);
```

**Comment by bean710** [comment]
We have to go by C89 (I think), which does not allow this. Trust me, I do it all the time and I get yelled at by the compiler.
