### ISSUE TITLE
variable spacing

### ISSUE THREAD

**Issue by ryankeener** [bean710/holbertonschool-low_level_programming#8]
https://github.com/bean710/holbertonschool-low_level_programming/blob/e9389a0d0cab75e5bf7757711ed41ee0431af45c/0x02-functions_nested_loops/100-times_table.c#L13-L16

It looks like there's a built-in limitation on the size of `n` but you could re-use your `getlen` function to support n of any size.

```c
    spacing = getlen(n*n) + 1;
```

**Comment by bean710** [comment]
I had to limit it for the checker, the program could handle anything, like you said, but the checker would fail me if anything above 15 even tried to print, whether or not it was correct.
